/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZeugnisseRouteImport } from './routes/zeugnisse'
import { Route as UeberDieseWebseiteRouteImport } from './routes/ueber-diese-webseite'
import { Route as SchnupperberichteRouteImport } from './routes/schnupperberichte'
import { Route as AlleDokumenteRouteImport } from './routes/alle-dokumente'
import { Route as IndexRouteImport } from './routes/index'

const ZeugnisseRoute = ZeugnisseRouteImport.update({
  id: '/zeugnisse',
  path: '/zeugnisse',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberDieseWebseiteRoute = UeberDieseWebseiteRouteImport.update({
  id: '/ueber-diese-webseite',
  path: '/ueber-diese-webseite',
  getParentRoute: () => rootRouteImport,
} as any)
const SchnupperberichteRoute = SchnupperberichteRouteImport.update({
  id: '/schnupperberichte',
  path: '/schnupperberichte',
  getParentRoute: () => rootRouteImport,
} as any)
const AlleDokumenteRoute = AlleDokumenteRouteImport.update({
  id: '/alle-dokumente',
  path: '/alle-dokumente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alle-dokumente': typeof AlleDokumenteRoute
  '/schnupperberichte': typeof SchnupperberichteRoute
  '/ueber-diese-webseite': typeof UeberDieseWebseiteRoute
  '/zeugnisse': typeof ZeugnisseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alle-dokumente': typeof AlleDokumenteRoute
  '/schnupperberichte': typeof SchnupperberichteRoute
  '/ueber-diese-webseite': typeof UeberDieseWebseiteRoute
  '/zeugnisse': typeof ZeugnisseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alle-dokumente': typeof AlleDokumenteRoute
  '/schnupperberichte': typeof SchnupperberichteRoute
  '/ueber-diese-webseite': typeof UeberDieseWebseiteRoute
  '/zeugnisse': typeof ZeugnisseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alle-dokumente'
    | '/schnupperberichte'
    | '/ueber-diese-webseite'
    | '/zeugnisse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alle-dokumente'
    | '/schnupperberichte'
    | '/ueber-diese-webseite'
    | '/zeugnisse'
  id:
    | '__root__'
    | '/'
    | '/alle-dokumente'
    | '/schnupperberichte'
    | '/ueber-diese-webseite'
    | '/zeugnisse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlleDokumenteRoute: typeof AlleDokumenteRoute
  SchnupperberichteRoute: typeof SchnupperberichteRoute
  UeberDieseWebseiteRoute: typeof UeberDieseWebseiteRoute
  ZeugnisseRoute: typeof ZeugnisseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zeugnisse': {
      id: '/zeugnisse'
      path: '/zeugnisse'
      fullPath: '/zeugnisse'
      preLoaderRoute: typeof ZeugnisseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-diese-webseite': {
      id: '/ueber-diese-webseite'
      path: '/ueber-diese-webseite'
      fullPath: '/ueber-diese-webseite'
      preLoaderRoute: typeof UeberDieseWebseiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schnupperberichte': {
      id: '/schnupperberichte'
      path: '/schnupperberichte'
      fullPath: '/schnupperberichte'
      preLoaderRoute: typeof SchnupperberichteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alle-dokumente': {
      id: '/alle-dokumente'
      path: '/alle-dokumente'
      fullPath: '/alle-dokumente'
      preLoaderRoute: typeof AlleDokumenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlleDokumenteRoute: AlleDokumenteRoute,
  SchnupperberichteRoute: SchnupperberichteRoute,
  UeberDieseWebseiteRoute: UeberDieseWebseiteRoute,
  ZeugnisseRoute: ZeugnisseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
